# Generated by Django 5.2.12 on 2026-03-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_destination_alter_itineraryitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='trips.city'),
            preserve_default=False,
        ),
    ]
