# version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: travel_db
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
      - static_volume:/code/staticfiles     # ← persist collected files
      - media_volume:/code/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    
      - DEBUG=1
      - DB_NAME=travel_db
      - DB_USER=travel_user
      - DB_PASSWORD=your_password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=travel_companion.settings
    command: gunicorn travel_companion.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ["/code/entrypoint.sh"]

volumes:
  postgres_data:
  static_volume:
  media_volume:



