# Generated by Django 5.2.12 on 2026-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=50),
            preserve_default=False,
        ),
    ]
