# Generated by Django 6.0.1 on 2026-03-11 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_matches', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('preferred_destinations', models.CharField(blank=True, max_length=255)),
                ('travel_style', models.CharField(choices=[('budget', 'Budget'), ('luxury', 'Luxury'), ('adventure', 'Adventure')], max_length=50)),
                ('pace', models.CharField(blank=True, choices=[('relaxed', 'Relaxed'), ('moderate', 'Moderate'), ('fast_paced', 'Fast_paced')], max_length=50)),
                ('accomodation_preference', models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('hotel', 'Hotel'), ('inn', 'Inn'), ('camping', 'Camping')], max_length=50)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('budget_level', models.IntegerField(default=5, help_text='0= cheap,  1 = expensive')),
                ('adventure_level', models.IntegerField(default=5, help_text='0= safe & calm, 10 = adventurous')),
                ('social_level', models.IntegerField(default=5, help_text='0 = solo_traveller, 10= group')),
                ('preference_vector', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
