# Generated by Django 5.2.12 on 2026-03-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycprofile',
            name='proof_of_address',
            field=models.FileField(blank=True, help_text='Utility bill, bank statement, lease agreement, etc.', null=True, upload_to='kyc/address_proofs/'),
        ),
    ]
