# Generated by Django 5.2.12 on 2026-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycprofile_proof_of_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='proof_of_address_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='proof_of_address_type',
            field=models.CharField(blank=True, choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('lease_agreement', 'Lease Agreement'), ('government_letter', 'Government Letter'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
