# Generated by Django 5.2.12 on 2026-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycprofile_proof_of_address_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
